### ISSUE TITLE
Summary/Technology/2018.11.5-量化笔试汇总 - 答案修改

### ISSUE THREAD

**Issue by sandrawing** [zhangjinzhi/Summary#1]
金融部分 单选题
原答案  7.aggregated accruals (using cash-flow method) = Net income(NI) - ( Cash from Financing(CFF) + Cash from Investments(CFI) )
正确答案 7.aggregated accruals (using cash-flow method) = Net income(NI) - ( Cash from Operating Activities(CFO) + Cash from Investments(CFI) )

Consecutive Sum
最优解：
https://leetcode.com/problems/consecutive-numbers-sum/solution/
Approach #3: Mathematical (Fast) [Accepted]

**Comment by zhangjinzhi** [comment]
感谢sandrawing指出错误，提供Consecutive Sum更优解法。
